Remove y18n due to CVE 2020 7774 part 5
foreversd/forever pull request #1112
Opened 2021-05-30 07:50 UTC by thenengah

2021-05-30 08:53 UTC, kibertoad requested changes
It's a pefectly valid behaviour to fail when non-existing file is referenced.
Instead, an empty config should be used when no config is specified.

2021-05-30 23:59 UTC, thenengah commented
> It's a pefectly valid behaviour to fail when non-existing file is referenced.
> Instead, an empty config should be used when no config is specified.

@kibertoad Got it; made updates, let me know what you think.

2021-05-31 06:14 UTC, kibertoad approved these changes

2021-05-31 06:14 UTC, merged

2021-05-31 08:43 UTC, thenengah commented
😄